vich_uploader:
    db_driver: orm

metadata:
        type: attribute

    mappings:
        DocPieces:
            uri_prefix: /DocPieces/documents
            upload_destination: '%kernel.project_dir%/public/DocPieces/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
