vich_uploader:
    db_driver: orm

    mappings: 
        DocPieces:
            uri_prefix: /DocPieces/documents
            upload_destination: '%kernel.project_dir%/public/DocPieces/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
