<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240307113924 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action_crm (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, attributed_to_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, mission LONGTEXT NOT NULL, objectif VARCHAR(255) NOT NULL, started_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', ended_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A62034BAFB88E14F (utilisateur_id), INDEX IDX_A62034BAA4AEAFEA (entreprise_id), INDEX IDX_A62034BA3288790B (attributed_to_id), INDEX IDX_A62034BAC34065BC (piste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE assureur (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, siteweb VARCHAR(255) DEFAULT NULL, rccm VARCHAR(255) DEFAULT NULL, idnat VARCHAR(255) DEFAULT NULL, licence VARCHAR(255) DEFAULT NULL, numimpot VARCHAR(255) DEFAULT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7B0E5955A4AEAFEA (entreprise_id), INDEX IDX_7B0E5955FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE automobile (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, police_id INT DEFAULT NULL, model VARCHAR(255) NOT NULL, marque VARCHAR(255) NOT NULL, annee VARCHAR(255) NOT NULL, puissance VARCHAR(255) NOT NULL, valeur NUMERIC(10, 2) DEFAULT NULL, nbsieges INT NOT NULL, utilite VARCHAR(255) NOT NULL, nature INT NOT NULL, plaque VARCHAR(255) NOT NULL, chassis VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BFCEA087A4AEAFEA (entreprise_id), INDEX IDX_BFCEA087FB88E14F (utilisateur_id), INDEX IDX_BFCEA08737E60BE1 (police_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE chargement (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, cotation_id INT DEFAULT NULL, type INT NOT NULL, description VARCHAR(255) DEFAULT NULL, montant DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_36328758FB88E14F (utilisateur_id), INDEX IDX_36328758A4AEAFEA (entreprise_id), INDEX IDX_363287585D14FAF0 (cotation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, siteweb VARCHAR(255) DEFAULT NULL, ispersonnemorale TINYINT(1) NOT NULL, rccm VARCHAR(255) DEFAULT NULL, idnat VARCHAR(255) DEFAULT NULL, numipot VARCHAR(255) DEFAULT NULL, secteur INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', exoneree TINYINT(1) DEFAULT NULL, INDEX IDX_C7440455A4AEAFEA (entreprise_id), INDEX IDX_C7440455FB88E14F (utilisateur_id), INDEX IDX_C7440455C34065BC (piste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE compte_bancaire (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, utilisateur_id INT DEFAULT NULL, intitule VARCHAR(255) NOT NULL, numero VARCHAR(255) NOT NULL, banque VARCHAR(255) NOT NULL, code_swift VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', code_monnaie VARCHAR(255) NOT NULL, INDEX IDX_50BC21DEA4AEAFEA (entreprise_id), INDEX IDX_50BC21DEFB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, poste VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4C62E638A4AEAFEA (entreprise_id), INDEX IDX_4C62E638FB88E14F (utilisateur_id), INDEX IDX_4C62E638C34065BC (piste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cotation (id INT AUTO_INCREMENT NOT NULL, piste_id INT DEFAULT NULL, assureur_id INT DEFAULT NULL, police_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, client_id INT DEFAULT NULL, partenaire_id INT DEFAULT NULL, utilisateur_id INT NOT NULL, gestionnaire_id INT DEFAULT NULL, assistant_id INT DEFAULT NULL, entreprise_id INT NOT NULL, nom VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_effet DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_expiration DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_operation DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_emition DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', duree_couverture INT NOT NULL, validated TINYINT(1) NOT NULL, tauxretrocompartenaire DOUBLE PRECISION NOT NULL, INDEX IDX_996DA944C34065BC (piste_id), INDEX IDX_996DA94480F7E20A (assureur_id), INDEX IDX_996DA94437E60BE1 (police_id), INDEX IDX_996DA944F347EFB (produit_id), INDEX IDX_996DA94419EB6921 (client_id), INDEX IDX_996DA94498DE13AC (partenaire_id), INDEX IDX_996DA944FB88E14F (utilisateur_id), INDEX IDX_996DA9446885AC1B (gestionnaire_id), INDEX IDX_996DA944E05387EF (assistant_id), INDEX IDX_996DA944A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_categorie (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B5A5EA55A4AEAFEA (entreprise_id), INDEX IDX_B5A5EA55FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_classeur (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B0EB9E01FB88E14F (utilisateur_id), INDEX IDX_B0EB9E01A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doc_piece (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, cotation_id INT DEFAULT NULL, police_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, action_crm_id INT DEFAULT NULL, paiement_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', nomfichier VARCHAR(255) DEFAULT NULL, taillefichier INT DEFAULT NULL, type INT DEFAULT NULL, INDEX IDX_2B236675FB88E14F (utilisateur_id), INDEX IDX_2B236675A4AEAFEA (entreprise_id), INDEX IDX_2B2366755D14FAF0 (cotation_id), INDEX IDX_2B23667537E60BE1 (police_id), INDEX IDX_2B236675C34065BC (piste_id), INDEX IDX_2B2366752ECC6D6F (action_crm_id), INDEX IDX_2B2366752A4C4478 (paiement_id), INDEX IDX_2B2366757F2DEE08 (facture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE element_facture (id INT AUTO_INCREMENT NOT NULL, tranche_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, utilisateur_id INT DEFAULT NULL, facture_id INT DEFAULT NULL, montant DOUBLE PRECISION DEFAULT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', idavenant INT DEFAULT NULL, typeavenant VARCHAR(255) DEFAULT NULL, include_prime TINYINT(1) DEFAULT NULL, include_com_locale TINYINT(1) DEFAULT NULL, include_com_fronting TINYINT(1) DEFAULT NULL, include_com_reassurance TINYINT(1) DEFAULT NULL, include_frais_gestion TINYINT(1) DEFAULT NULL, include_retro_com TINYINT(1) DEFAULT NULL, include_taxe_courtier TINYINT(1) DEFAULT NULL, include_taxe_assureur TINYINT(1) DEFAULT NULL, INDEX IDX_96D2444B76F6B31 (tranche_id), INDEX IDX_96D2444A4AEAFEA (entreprise_id), INDEX IDX_96D2444FB88E14F (utilisateur_id), INDEX IDX_96D24447F2DEE08 (facture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, telephone VARCHAR(255) DEFAULT NULL, rccm VARCHAR(255) DEFAULT NULL, idnat VARCHAR(255) DEFAULT NULL, numimpot VARCHAR(255) DEFAULT NULL, secteur INT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D19FA60FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etape_crm (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, nom VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_5823919EFB88E14F (utilisateur_id), INDEX IDX_5823919EA4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etape_sinistre (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', indice INT DEFAULT NULL, INDEX IDX_E4F61898A4AEAFEA (entreprise_id), INDEX IDX_E4F61898FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expert (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, siteweb VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', telephone VARCHAR(255) NOT NULL, INDEX IDX_4F1B9342A4AEAFEA (entreprise_id), INDEX IDX_4F1B9342FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, partenaire_id INT DEFAULT NULL, assureur_id INT DEFAULT NULL, piece_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', destination INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, total_recu DOUBLE PRECISION DEFAULT NULL, autre_tiers VARCHAR(255) DEFAULT NULL, signed_by VARCHAR(255) DEFAULT NULL, poste_signed_by VARCHAR(255) DEFAULT NULL, total_solde DOUBLE PRECISION DEFAULT NULL, status INT DEFAULT NULL, INDEX IDX_FE866410FB88E14F (utilisateur_id), INDEX IDX_FE866410A4AEAFEA (entreprise_id), INDEX IDX_FE86641098DE13AC (partenaire_id), INDEX IDX_FE86641080F7E20A (assureur_id), UNIQUE INDEX UNIQ_FE866410C40FCFA8 (piece_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture_compte_bancaire (facture_id INT NOT NULL, compte_bancaire_id INT NOT NULL, INDEX IDX_98CB295B7F2DEE08 (facture_id), INDEX IDX_98CB295BAF1E371E (compte_bancaire_id), PRIMARY KEY(facture_id, compte_bancaire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE feedback_crm (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, action_crm_id INT DEFAULT NULL, message VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', closed TINYINT(1) DEFAULT NULL, INDEX IDX_83009D42FB88E14F (utilisateur_id), INDEX IDX_83009D42A4AEAFEA (entreprise_id), INDEX IDX_83009D422ECC6D6F (action_crm_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE monnaie (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, tauxusd NUMERIC(10, 2) NOT NULL, islocale TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', fonction INT NOT NULL, INDEX IDX_B3A6E2E6FB88E14F (utilisateur_id), INDEX IDX_B3A6E2E6A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement (id INT AUTO_INCREMENT NOT NULL, facture_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, utilisateur_id INT DEFAULT NULL, compte_bancaire_id INT DEFAULT NULL, paid_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', montant DOUBLE PRECISION NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', destination INT NOT NULL, type INT DEFAULT NULL, INDEX IDX_B1DC7A1E7F2DEE08 (facture_id), INDEX IDX_B1DC7A1EA4AEAFEA (entreprise_id), INDEX IDX_B1DC7A1EFB88E14F (utilisateur_id), INDEX IDX_B1DC7A1EAF1E371E (compte_bancaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partenaire (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, part NUMERIC(10, 2) NOT NULL, adresse VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, siteweb VARCHAR(255) DEFAULT NULL, rccm VARCHAR(255) DEFAULT NULL, idnat VARCHAR(255) DEFAULT NULL, numimpot VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_32FFA373A4AEAFEA (entreprise_id), INDEX IDX_32FFA373FB88E14F (utilisateur_id), INDEX IDX_32FFA373C34065BC (piste_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE piste (id INT AUTO_INCREMENT NOT NULL, police_id INT DEFAULT NULL, client_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, partenaire_id INT DEFAULT NULL, gestionnaire_id INT DEFAULT NULL, assistant_id INT DEFAULT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, nom VARCHAR(255) NOT NULL, objectif VARCHAR(255) NOT NULL, expired_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', typeavenant VARCHAR(255) DEFAULT NULL, etape INT DEFAULT NULL, montant DOUBLE PRECISION DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_59E2507737E60BE1 (police_id), INDEX IDX_59E2507719EB6921 (client_id), INDEX IDX_59E25077F347EFB (produit_id), INDEX IDX_59E2507798DE13AC (partenaire_id), INDEX IDX_59E250776885AC1B (gestionnaire_id), INDEX IDX_59E25077E05387EF (assistant_id), INDEX IDX_59E25077FB88E14F (utilisateur_id), INDEX IDX_59E25077A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE police (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, piste_id INT DEFAULT NULL, cotation_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', id_avenant INT NOT NULL, dateoperation DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', dateemission DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', dateeffet DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E47C5959A4AEAFEA (entreprise_id), INDEX IDX_E47C5959FB88E14F (utilisateur_id), INDEX IDX_E47C5959C34065BC (piste_id), UNIQUE INDEX UNIQ_E47C59595D14FAF0 (cotation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE preference (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', crm_taille INT DEFAULT NULL, crm_missions LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', crm_feedbacks LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', crm_cotations LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', crm_etapes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', crm_pistes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', apparence INT NOT NULL, pro_taille INT NOT NULL, pro_assureurs LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_automobiles LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_contacts LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_clients LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_partenaires LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_polices LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_produits LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_taille INT NOT NULL, fin_taxes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_monnaies LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_commissions_payees LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_retrocommissions_payees LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_taxes_payees LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sin_taille INT NOT NULL, sin_commentaires LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sin_etapes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sin_experts LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sin_sinistres LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', sin_victimes LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', bib_taille INT NOT NULL, bib_categories LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', bib_classeurs LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', bib_pieces LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', par_taille INT NOT NULL, par_utilisateurs LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_factures LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_element_factures LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_compte_bancaires LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_paiement LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', fin_revenu LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', prod_chargement LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', pro_tranches LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_5D69B053FB88E14F (utilisateur_id), INDEX IDX_5D69B053A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, code VARCHAR(4) NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, tauxarca NUMERIC(10, 2) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', abonnement TINYINT(1) NOT NULL, obligatoire TINYINT(1) NOT NULL, iard TINYINT(1) NOT NULL, INDEX IDX_29A5EC27A4AEAFEA (entreprise_id), INDEX IDX_29A5EC27FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revenu (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, cotation_id INT DEFAULT NULL, type INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', partageable INT NOT NULL, taxable INT NOT NULL, base INT NOT NULL, taux DOUBLE PRECISION NOT NULL, montant_flat DOUBLE PRECISION NOT NULL, isparttranche TINYINT(1) DEFAULT NULL, ispartclient TINYINT(1) DEFAULT NULL, date_effet DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_expiration DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_operation DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_emition DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7DA3C045FB88E14F (utilisateur_id), INDEX IDX_7DA3C045A4AEAFEA (entreprise_id), INDEX IDX_7DA3C0455D14FAF0 (cotation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sinistre (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, entreprise_id INT NOT NULL, police_id INT DEFAULT NULL, etape_id INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', cout DOUBLE PRECISION NOT NULL, montant_paye DOUBLE PRECISION NOT NULL, occured_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', paid_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', numero VARCHAR(255) DEFAULT NULL, INDEX IDX_F5AC7A67FB88E14F (utilisateur_id), INDEX IDX_F5AC7A67A4AEAFEA (entreprise_id), INDEX IDX_F5AC7A6737E60BE1 (police_id), INDEX IDX_F5AC7A674A8CA2AD (etape_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sinistre_expert (sinistre_id INT NOT NULL, expert_id INT NOT NULL, INDEX IDX_56EFBC0F216966DF (sinistre_id), INDEX IDX_56EFBC0FC5568CE4 (expert_id), PRIMARY KEY(sinistre_id, expert_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE taxe (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, taux_iard NUMERIC(10, 2) NOT NULL, taux_vie NUMERIC(10, 2) NOT NULL, organisation VARCHAR(255) NOT NULL, payableparcourtier TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_56322FE9FB88E14F (utilisateur_id), INDEX IDX_56322FE9A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tranche (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, cotation_id INT DEFAULT NULL, taux DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', nom VARCHAR(255) NOT NULL, duree INT NOT NULL, started_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', ended_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_effet DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_expiration DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_operation DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', date_emition DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_66675840FB88E14F (utilisateur_id), INDEX IDX_66675840A4AEAFEA (entreprise_id), INDEX IDX_666758405D14FAF0 (cotation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, nom VARCHAR(50) NOT NULL, pseudo VARCHAR(20) NOT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_1D1C63B3E7927C74 (email), INDEX IDX_1D1C63B3FB88E14F (utilisateur_id), INDEX IDX_1D1C63B3A4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE victime (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT NOT NULL, utilisateur_id INT DEFAULT NULL, sinistre_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_AD6D2E39A4AEAFEA (entreprise_id), INDEX IDX_AD6D2E39FB88E14F (utilisateur_id), INDEX IDX_AD6D2E39216966DF (sinistre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE action_crm ADD CONSTRAINT FK_A62034BAFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE action_crm ADD CONSTRAINT FK_A62034BAA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE action_crm ADD CONSTRAINT FK_A62034BA3288790B FOREIGN KEY (attributed_to_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE action_crm ADD CONSTRAINT FK_A62034BAC34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE assureur ADD CONSTRAINT FK_7B0E5955A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE assureur ADD CONSTRAINT FK_7B0E5955FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE automobile ADD CONSTRAINT FK_BFCEA087A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE automobile ADD CONSTRAINT FK_BFCEA087FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE automobile ADD CONSTRAINT FK_BFCEA08737E60BE1 FOREIGN KEY (police_id) REFERENCES police (id)');
        $this->addSql('ALTER TABLE chargement ADD CONSTRAINT FK_36328758FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE chargement ADD CONSTRAINT FK_36328758A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE chargement ADD CONSTRAINT FK_363287585D14FAF0 FOREIGN KEY (cotation_id) REFERENCES cotation (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE compte_bancaire ADD CONSTRAINT FK_50BC21DEA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE compte_bancaire ADD CONSTRAINT FK_50BC21DEFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA944C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA94480F7E20A FOREIGN KEY (assureur_id) REFERENCES assureur (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA94437E60BE1 FOREIGN KEY (police_id) REFERENCES police (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA944F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA94419EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA94498DE13AC FOREIGN KEY (partenaire_id) REFERENCES partenaire (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA944FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA9446885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA944E05387EF FOREIGN KEY (assistant_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE cotation ADD CONSTRAINT FK_996DA944A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE doc_categorie ADD CONSTRAINT FK_B5A5EA55A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE doc_categorie ADD CONSTRAINT FK_B5A5EA55FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE doc_classeur ADD CONSTRAINT FK_B0EB9E01FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE doc_classeur ADD CONSTRAINT FK_B0EB9E01A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B236675FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B236675A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B2366755D14FAF0 FOREIGN KEY (cotation_id) REFERENCES cotation (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B23667537E60BE1 FOREIGN KEY (police_id) REFERENCES police (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B236675C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B2366752ECC6D6F FOREIGN KEY (action_crm_id) REFERENCES action_crm (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B2366752A4C4478 FOREIGN KEY (paiement_id) REFERENCES paiement (id)');
        $this->addSql('ALTER TABLE doc_piece ADD CONSTRAINT FK_2B2366757F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE element_facture ADD CONSTRAINT FK_96D2444B76F6B31 FOREIGN KEY (tranche_id) REFERENCES tranche (id)');
        $this->addSql('ALTER TABLE element_facture ADD CONSTRAINT FK_96D2444A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE element_facture ADD CONSTRAINT FK_96D2444FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE element_facture ADD CONSTRAINT FK_96D24447F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE etape_crm ADD CONSTRAINT FK_5823919EFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE etape_crm ADD CONSTRAINT FK_5823919EA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE etape_sinistre ADD CONSTRAINT FK_E4F61898A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE etape_sinistre ADD CONSTRAINT FK_E4F61898FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE expert ADD CONSTRAINT FK_4F1B9342A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE expert ADD CONSTRAINT FK_4F1B9342FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641098DE13AC FOREIGN KEY (partenaire_id) REFERENCES partenaire (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641080F7E20A FOREIGN KEY (assureur_id) REFERENCES assureur (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410C40FCFA8 FOREIGN KEY (piece_id) REFERENCES doc_piece (id)');
        $this->addSql('ALTER TABLE facture_compte_bancaire ADD CONSTRAINT FK_98CB295B7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facture_compte_bancaire ADD CONSTRAINT FK_98CB295BAF1E371E FOREIGN KEY (compte_bancaire_id) REFERENCES compte_bancaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE feedback_crm ADD CONSTRAINT FK_83009D42FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE feedback_crm ADD CONSTRAINT FK_83009D42A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE feedback_crm ADD CONSTRAINT FK_83009D422ECC6D6F FOREIGN KEY (action_crm_id) REFERENCES action_crm (id)');
        $this->addSql('ALTER TABLE monnaie ADD CONSTRAINT FK_B3A6E2E6FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE monnaie ADD CONSTRAINT FK_B3A6E2E6A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EAF1E371E FOREIGN KEY (compte_bancaire_id) REFERENCES compte_bancaire (id)');
        $this->addSql('ALTER TABLE partenaire ADD CONSTRAINT FK_32FFA373A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE partenaire ADD CONSTRAINT FK_32FFA373FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE partenaire ADD CONSTRAINT FK_32FFA373C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E2507737E60BE1 FOREIGN KEY (police_id) REFERENCES police (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E2507719EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E25077F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E2507798DE13AC FOREIGN KEY (partenaire_id) REFERENCES partenaire (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E250776885AC1B FOREIGN KEY (gestionnaire_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E25077E05387EF FOREIGN KEY (assistant_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E25077FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE piste ADD CONSTRAINT FK_59E25077A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE police ADD CONSTRAINT FK_E47C5959A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE police ADD CONSTRAINT FK_E47C5959FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE police ADD CONSTRAINT FK_E47C5959C34065BC FOREIGN KEY (piste_id) REFERENCES piste (id)');
        $this->addSql('ALTER TABLE police ADD CONSTRAINT FK_E47C59595D14FAF0 FOREIGN KEY (cotation_id) REFERENCES cotation (id)');
        $this->addSql('ALTER TABLE preference ADD CONSTRAINT FK_5D69B053FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE preference ADD CONSTRAINT FK_5D69B053A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE revenu ADD CONSTRAINT FK_7DA3C045FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE revenu ADD CONSTRAINT FK_7DA3C045A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE revenu ADD CONSTRAINT FK_7DA3C0455D14FAF0 FOREIGN KEY (cotation_id) REFERENCES cotation (id)');
        $this->addSql('ALTER TABLE sinistre ADD CONSTRAINT FK_F5AC7A67FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE sinistre ADD CONSTRAINT FK_F5AC7A67A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE sinistre ADD CONSTRAINT FK_F5AC7A6737E60BE1 FOREIGN KEY (police_id) REFERENCES police (id)');
        $this->addSql('ALTER TABLE sinistre ADD CONSTRAINT FK_F5AC7A674A8CA2AD FOREIGN KEY (etape_id) REFERENCES etape_sinistre (id)');
        $this->addSql('ALTER TABLE sinistre_expert ADD CONSTRAINT FK_56EFBC0F216966DF FOREIGN KEY (sinistre_id) REFERENCES sinistre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sinistre_expert ADD CONSTRAINT FK_56EFBC0FC5568CE4 FOREIGN KEY (expert_id) REFERENCES expert (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE taxe ADD CONSTRAINT FK_56322FE9FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE taxe ADD CONSTRAINT FK_56322FE9A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE tranche ADD CONSTRAINT FK_66675840FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE tranche ADD CONSTRAINT FK_66675840A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE tranche ADD CONSTRAINT FK_666758405D14FAF0 FOREIGN KEY (cotation_id) REFERENCES cotation (id)');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE victime ADD CONSTRAINT FK_AD6D2E39A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE victime ADD CONSTRAINT FK_AD6D2E39FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE victime ADD CONSTRAINT FK_AD6D2E39216966DF FOREIGN KEY (sinistre_id) REFERENCES sinistre (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action_crm DROP FOREIGN KEY FK_A62034BAFB88E14F');
        $this->addSql('ALTER TABLE action_crm DROP FOREIGN KEY FK_A62034BAA4AEAFEA');
        $this->addSql('ALTER TABLE action_crm DROP FOREIGN KEY FK_A62034BA3288790B');
        $this->addSql('ALTER TABLE action_crm DROP FOREIGN KEY FK_A62034BAC34065BC');
        $this->addSql('ALTER TABLE assureur DROP FOREIGN KEY FK_7B0E5955A4AEAFEA');
        $this->addSql('ALTER TABLE assureur DROP FOREIGN KEY FK_7B0E5955FB88E14F');
        $this->addSql('ALTER TABLE automobile DROP FOREIGN KEY FK_BFCEA087A4AEAFEA');
        $this->addSql('ALTER TABLE automobile DROP FOREIGN KEY FK_BFCEA087FB88E14F');
        $this->addSql('ALTER TABLE automobile DROP FOREIGN KEY FK_BFCEA08737E60BE1');
        $this->addSql('ALTER TABLE chargement DROP FOREIGN KEY FK_36328758FB88E14F');
        $this->addSql('ALTER TABLE chargement DROP FOREIGN KEY FK_36328758A4AEAFEA');
        $this->addSql('ALTER TABLE chargement DROP FOREIGN KEY FK_363287585D14FAF0');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A4AEAFEA');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455FB88E14F');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455C34065BC');
        $this->addSql('ALTER TABLE compte_bancaire DROP FOREIGN KEY FK_50BC21DEA4AEAFEA');
        $this->addSql('ALTER TABLE compte_bancaire DROP FOREIGN KEY FK_50BC21DEFB88E14F');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638A4AEAFEA');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638FB88E14F');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638C34065BC');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA944C34065BC');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA94480F7E20A');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA94437E60BE1');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA944F347EFB');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA94419EB6921');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA94498DE13AC');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA944FB88E14F');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA9446885AC1B');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA944E05387EF');
        $this->addSql('ALTER TABLE cotation DROP FOREIGN KEY FK_996DA944A4AEAFEA');
        $this->addSql('ALTER TABLE doc_categorie DROP FOREIGN KEY FK_B5A5EA55A4AEAFEA');
        $this->addSql('ALTER TABLE doc_categorie DROP FOREIGN KEY FK_B5A5EA55FB88E14F');
        $this->addSql('ALTER TABLE doc_classeur DROP FOREIGN KEY FK_B0EB9E01FB88E14F');
        $this->addSql('ALTER TABLE doc_classeur DROP FOREIGN KEY FK_B0EB9E01A4AEAFEA');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B236675FB88E14F');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B236675A4AEAFEA');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B2366755D14FAF0');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B23667537E60BE1');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B236675C34065BC');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B2366752ECC6D6F');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B2366752A4C4478');
        $this->addSql('ALTER TABLE doc_piece DROP FOREIGN KEY FK_2B2366757F2DEE08');
        $this->addSql('ALTER TABLE element_facture DROP FOREIGN KEY FK_96D2444B76F6B31');
        $this->addSql('ALTER TABLE element_facture DROP FOREIGN KEY FK_96D2444A4AEAFEA');
        $this->addSql('ALTER TABLE element_facture DROP FOREIGN KEY FK_96D2444FB88E14F');
        $this->addSql('ALTER TABLE element_facture DROP FOREIGN KEY FK_96D24447F2DEE08');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60FB88E14F');
        $this->addSql('ALTER TABLE etape_crm DROP FOREIGN KEY FK_5823919EFB88E14F');
        $this->addSql('ALTER TABLE etape_crm DROP FOREIGN KEY FK_5823919EA4AEAFEA');
        $this->addSql('ALTER TABLE etape_sinistre DROP FOREIGN KEY FK_E4F61898A4AEAFEA');
        $this->addSql('ALTER TABLE etape_sinistre DROP FOREIGN KEY FK_E4F61898FB88E14F');
        $this->addSql('ALTER TABLE expert DROP FOREIGN KEY FK_4F1B9342A4AEAFEA');
        $this->addSql('ALTER TABLE expert DROP FOREIGN KEY FK_4F1B9342FB88E14F');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410FB88E14F');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410A4AEAFEA');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641098DE13AC');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641080F7E20A');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410C40FCFA8');
        $this->addSql('ALTER TABLE facture_compte_bancaire DROP FOREIGN KEY FK_98CB295B7F2DEE08');
        $this->addSql('ALTER TABLE facture_compte_bancaire DROP FOREIGN KEY FK_98CB295BAF1E371E');
        $this->addSql('ALTER TABLE feedback_crm DROP FOREIGN KEY FK_83009D42FB88E14F');
        $this->addSql('ALTER TABLE feedback_crm DROP FOREIGN KEY FK_83009D42A4AEAFEA');
        $this->addSql('ALTER TABLE feedback_crm DROP FOREIGN KEY FK_83009D422ECC6D6F');
        $this->addSql('ALTER TABLE monnaie DROP FOREIGN KEY FK_B3A6E2E6FB88E14F');
        $this->addSql('ALTER TABLE monnaie DROP FOREIGN KEY FK_B3A6E2E6A4AEAFEA');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E7F2DEE08');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1EA4AEAFEA');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1EFB88E14F');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1EAF1E371E');
        $this->addSql('ALTER TABLE partenaire DROP FOREIGN KEY FK_32FFA373A4AEAFEA');
        $this->addSql('ALTER TABLE partenaire DROP FOREIGN KEY FK_32FFA373FB88E14F');
        $this->addSql('ALTER TABLE partenaire DROP FOREIGN KEY FK_32FFA373C34065BC');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E2507737E60BE1');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E2507719EB6921');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E25077F347EFB');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E2507798DE13AC');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E250776885AC1B');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E25077E05387EF');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E25077FB88E14F');
        $this->addSql('ALTER TABLE piste DROP FOREIGN KEY FK_59E25077A4AEAFEA');
        $this->addSql('ALTER TABLE police DROP FOREIGN KEY FK_E47C5959A4AEAFEA');
        $this->addSql('ALTER TABLE police DROP FOREIGN KEY FK_E47C5959FB88E14F');
        $this->addSql('ALTER TABLE police DROP FOREIGN KEY FK_E47C5959C34065BC');
        $this->addSql('ALTER TABLE police DROP FOREIGN KEY FK_E47C59595D14FAF0');
        $this->addSql('ALTER TABLE preference DROP FOREIGN KEY FK_5D69B053FB88E14F');
        $this->addSql('ALTER TABLE preference DROP FOREIGN KEY FK_5D69B053A4AEAFEA');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC27A4AEAFEA');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC27FB88E14F');
        $this->addSql('ALTER TABLE revenu DROP FOREIGN KEY FK_7DA3C045FB88E14F');
        $this->addSql('ALTER TABLE revenu DROP FOREIGN KEY FK_7DA3C045A4AEAFEA');
        $this->addSql('ALTER TABLE revenu DROP FOREIGN KEY FK_7DA3C0455D14FAF0');
        $this->addSql('ALTER TABLE sinistre DROP FOREIGN KEY FK_F5AC7A67FB88E14F');
        $this->addSql('ALTER TABLE sinistre DROP FOREIGN KEY FK_F5AC7A67A4AEAFEA');
        $this->addSql('ALTER TABLE sinistre DROP FOREIGN KEY FK_F5AC7A6737E60BE1');
        $this->addSql('ALTER TABLE sinistre DROP FOREIGN KEY FK_F5AC7A674A8CA2AD');
        $this->addSql('ALTER TABLE sinistre_expert DROP FOREIGN KEY FK_56EFBC0F216966DF');
        $this->addSql('ALTER TABLE sinistre_expert DROP FOREIGN KEY FK_56EFBC0FC5568CE4');
        $this->addSql('ALTER TABLE taxe DROP FOREIGN KEY FK_56322FE9FB88E14F');
        $this->addSql('ALTER TABLE taxe DROP FOREIGN KEY FK_56322FE9A4AEAFEA');
        $this->addSql('ALTER TABLE tranche DROP FOREIGN KEY FK_66675840FB88E14F');
        $this->addSql('ALTER TABLE tranche DROP FOREIGN KEY FK_66675840A4AEAFEA');
        $this->addSql('ALTER TABLE tranche DROP FOREIGN KEY FK_666758405D14FAF0');
        $this->addSql('ALTER TABLE utilisateur DROP FOREIGN KEY FK_1D1C63B3FB88E14F');
        $this->addSql('ALTER TABLE utilisateur DROP FOREIGN KEY FK_1D1C63B3A4AEAFEA');
        $this->addSql('ALTER TABLE victime DROP FOREIGN KEY FK_AD6D2E39A4AEAFEA');
        $this->addSql('ALTER TABLE victime DROP FOREIGN KEY FK_AD6D2E39FB88E14F');
        $this->addSql('ALTER TABLE victime DROP FOREIGN KEY FK_AD6D2E39216966DF');
        $this->addSql('DROP TABLE action_crm');
        $this->addSql('DROP TABLE assureur');
        $this->addSql('DROP TABLE automobile');
        $this->addSql('DROP TABLE chargement');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE compte_bancaire');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE cotation');
        $this->addSql('DROP TABLE doc_categorie');
        $this->addSql('DROP TABLE doc_classeur');
        $this->addSql('DROP TABLE doc_piece');
        $this->addSql('DROP TABLE element_facture');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE etape_crm');
        $this->addSql('DROP TABLE etape_sinistre');
        $this->addSql('DROP TABLE expert');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE facture_compte_bancaire');
        $this->addSql('DROP TABLE feedback_crm');
        $this->addSql('DROP TABLE monnaie');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE partenaire');
        $this->addSql('DROP TABLE piste');
        $this->addSql('DROP TABLE police');
        $this->addSql('DROP TABLE preference');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE revenu');
        $this->addSql('DROP TABLE sinistre');
        $this->addSql('DROP TABLE sinistre_expert');
        $this->addSql('DROP TABLE taxe');
        $this->addSql('DROP TABLE tranche');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE victime');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
